require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CookbooksController do

  # This should return the minimal set of attributes required to create a valid
  # Cookbook. As you add validations to Cookbook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CookbooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cookbooks as @cookbooks" do
      cookbook = Cookbook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cookbooks).should eq([cookbook])
    end
  end

  describe "GET show" do
    it "assigns the requested cookbook as @cookbook" do
      cookbook = Cookbook.create! valid_attributes
      get :show, {:id => cookbook.to_param}, valid_session
      assigns(:cookbook).should eq(cookbook)
    end
  end

  describe "GET new" do
    it "assigns a new cookbook as @cookbook" do
      get :new, {}, valid_session
      assigns(:cookbook).should be_a_new(Cookbook)
    end
  end

  describe "GET edit" do
    it "assigns the requested cookbook as @cookbook" do
      cookbook = Cookbook.create! valid_attributes
      get :edit, {:id => cookbook.to_param}, valid_session
      assigns(:cookbook).should eq(cookbook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cookbook" do
        expect {
          post :create, {:cookbook => valid_attributes}, valid_session
        }.to change(Cookbook, :count).by(1)
      end

      it "assigns a newly created cookbook as @cookbook" do
        post :create, {:cookbook => valid_attributes}, valid_session
        assigns(:cookbook).should be_a(Cookbook)
        assigns(:cookbook).should be_persisted
      end

      it "redirects to the created cookbook" do
        post :create, {:cookbook => valid_attributes}, valid_session
        response.should redirect_to(Cookbook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cookbook as @cookbook" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cookbook.any_instance.stub(:save).and_return(false)
        post :create, {:cookbook => {  }}, valid_session
        assigns(:cookbook).should be_a_new(Cookbook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cookbook.any_instance.stub(:save).and_return(false)
        post :create, {:cookbook => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cookbook" do
        cookbook = Cookbook.create! valid_attributes
        # Assuming there are no other cookbooks in the database, this
        # specifies that the Cookbook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cookbook.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => cookbook.to_param, :cookbook => { "these" => "params" }}, valid_session
      end

      it "assigns the requested cookbook as @cookbook" do
        cookbook = Cookbook.create! valid_attributes
        put :update, {:id => cookbook.to_param, :cookbook => valid_attributes}, valid_session
        assigns(:cookbook).should eq(cookbook)
      end

      it "redirects to the cookbook" do
        cookbook = Cookbook.create! valid_attributes
        put :update, {:id => cookbook.to_param, :cookbook => valid_attributes}, valid_session
        response.should redirect_to(cookbook)
      end
    end

    describe "with invalid params" do
      it "assigns the cookbook as @cookbook" do
        cookbook = Cookbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cookbook.any_instance.stub(:save).and_return(false)
        put :update, {:id => cookbook.to_param, :cookbook => {  }}, valid_session
        assigns(:cookbook).should eq(cookbook)
      end

      it "re-renders the 'edit' template" do
        cookbook = Cookbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cookbook.any_instance.stub(:save).and_return(false)
        put :update, {:id => cookbook.to_param, :cookbook => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cookbook" do
      cookbook = Cookbook.create! valid_attributes
      expect {
        delete :destroy, {:id => cookbook.to_param}, valid_session
      }.to change(Cookbook, :count).by(-1)
    end

    it "redirects to the cookbooks list" do
      cookbook = Cookbook.create! valid_attributes
      delete :destroy, {:id => cookbook.to_param}, valid_session
      response.should redirect_to(cookbooks_url)
    end
  end

end
